creation_timestamp: 1782393704940
current_stage: None
deployment_job_state: null
description: null
last_updated_timestamp: 1782393704940
model_id: m-4daacf4759994d459dabf740977517f6
name: churn-lgbm-optimized
run_id: a49bad03f8264587b17022b1e08e1507
run_link: null
source: models:/m-4daacf4759994d459dabf740977517f6
status: READY
status_message: null
storage_location: file:///Users/matheusfiletti/Desktop/eng_de_machine_learning/Tech-Challenge-Fase1/models/573940291247750367/models/m-4daacf4759994d459dabf740977517f6/artifacts
user_id: null
version: 2
workspace: default
