aliases: {}
creation_timestamp: 1782224257857
deployment_job_id: null
deployment_job_state: null
description: null
last_updated_timestamp: 1782394141244
name: churn-logistic-baseline
workspace: default
